#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

set -x

eval "$(direnv export bash)"

cargo fmt

cargo build

cargo clippy -- -D warnings

test-harness target/debug/context-grep
